# Generated by Django 4.2.4 on 2023-08-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horse_app', '0001_initial'),
        ('careList_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelist',
            name='horse_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_list_id', to='horse_app.horse'),
        ),
    ]
