# Generated by Django 4.2.4 on 2023-08-11 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careList_app', '0005_alter_carelist_farrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelist',
            name='farrier',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
