# Generated by Django 4.2.4 on 2023-08-11 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careList_app', '0003_alter_carelist_horse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelist',
            name='farrier',
            field=models.DateField(default=datetime.datetime(2023, 8, 11, 18, 35, 5, 688742)),
        ),
        migrations.AlterField(
            model_name='carelist',
            name='feed_type',
            field=models.CharField(default='hay'),
        ),
        migrations.AlterField(
            model_name='carelist',
            name='supplements',
            field=models.CharField(default='no supplements'),
        ),
    ]
