# Generated by Django 4.2.4 on 2023-08-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horse_app', '0001_initial'),
        ('stable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='stable_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_id', to='stable_app.stable'),
        ),
    ]
