# Generated by Django 4.2.4 on 2023-08-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField()),
                ('is_complete', models.BooleanField(default=False)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='list_app.list')),
            ],
        ),
    ]
