# Generated by Django 4.2.4 on 2023-08-09 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stable_app', '0003_stable_name_alter_stable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stable',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stable_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
